#!/bin/sh
#blender -b "crema cafe 4.blend" -S 01 -f 1
#blender -b "crema cafe 4.blend" -S 02 -f 1
#blender -b "crema cafe 4.blend" -S 03 -f 1
#blender -b "crema cafe 4.blend" -S 04 -f 1
#blender -b "crema cafe 4.blend" -S 05 -f 1
#blender -b "crema cafe 4.blend" -S 06 -f 1
#blender -b "crema cafe 4.blend" -S 07 -f 1
#blender -b "crema cafe 4.blend" -S 08 -f 1
#blender -b "crema cafe 5.blend" -S 01 -f 1
blender -b "crema cafe 5.blend" -S 02 -f 1
blender -b "crema cafe 5.blend" -S 03 -f 1
blender -b "crema cafe 5.blend" -S 04 -f 1
blender -b "crema cafe 5.blend" -S 05 -f 1
blender -b "crema cafe 5.blend" -S 06 -f 1
blender -b "crema cafe 5.blend" -S 07 -f 1
blender -b "crema cafe 5.blend" -S 08 -f 1
